// MVCApi.Client/src/components/ProductForm.tsx
import React, { useEffect, useState } from 'react'
import { Form, Row, Col, Button } from 'react-bootstrap'
import { isNull } from 'util'
import { CreateProduct, ProductApi, CategoryDto, CategoryApi } from '../api'

interface CreateProductErrors {
    name?: string | null,
    description?: string | null,
    image?: string | null,
    price?: string | null,
    category?: string | null
}

export function ProductForm() {
    const [product, setProduct] = useState<CreateProduct>({})
    const [errors, setErrors] = useState<CreateProductErrors>({})
    const [categories, setCategories] = useState<CategoryDto[]>([])
    const [category, setCategory] = useState<CategoryDto | null>(null)
    const [response, setResponse] = useState<string>('')

    const validation = (): boolean => {

        let valid = true;
        let newErrors: CreateProductErrors = {};

        if (!product.name) {
            newErrors.name = "Product name must be set!";
            valid = false;
        } else {
            // Additional checks
        }

        if (!product.description) {
            newErrors.description= "Description must be set"
            valid = false
        } else {
            // Additional checks
        }

        if (!product.image) {
            newErrors.image= "Image must be set"
            valid = false
        } else {
            // Additional checks
        }

        if (!product.price) {
            newErrors.price = "Product image must be set!";
            valid = false;
        } else {
            if (product.price.valueOf() < 0) {
                newErrors.price = "Price must be greater than 0";
                valid = false;
            }
        }

        if (!category) {
            valid = false;
            newErrors.category = "You must choose a category"
        }

        setErrors(newErrors)

        return valid;
    }

    const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault()
        event.stopPropagation()

        if (validation()) {
            const api = new ProductApi()
            const categoryApi = new CategoryApi()
            
                api.apiProductCreateProductPost({ createProduct: product }).then(
                    response => {
                        categoryApi.apiCategoryAddProductToCategoryPut({
                            addProductToCategory: { categoryId: category?.id, productId: response.replaceAll('"', '') }
                        }).then(() => setResponse("Succesfully added a product"))
                        .catch(() => setResponse("Couldn't add product to category"))
                    }
                ).catch(() => setResponse("Something went wrong, try again"))            
        }
    }

    const handleChangeProduct = (event: React.ChangeEvent<HTMLInputElement>) => {
        setProduct({ ...product, [event.target.name]: event.target.value })
        console.log(product)
    }

    useEffect(() => {
        const api = new CategoryApi()
        api.apiCategoryGetAllCategoriesGet()
            .then(response => setCategories(response))
    }, [])

    return (

        <Form noValidate onSubmit={(e) => handleSubmit(e)}>
            <Row className="mb-2">
                <Form.Group as={Col}>
                    <Form.Label>Product name</Form.Label>
                    <Form.Control isInvalid={!!errors['name']} required type="text" placeholder='Name of a product' name='name' onChange={handleChangeProduct} />
                    <Form.Control.Feedback type='invalid'>{errors['name']}</Form.Control.Feedback>
                </Form.Group>
            </Row>
            <Row className="mb-2">
                <Form.Group as={Col}>
                    <Form.Label>Product description</Form.Label>
                    <Form.Control isInvalid={!!errors['description']} required type="text" placeholder='Product description' name='description' onChange={handleChangeProduct} />
                    <Form.Control.Feedback type='invalid'>{errors['description']}</Form.Control.Feedback>
                </Form.Group>
            </Row>
            <Row className="mb-2">
                <Form.Group as={Col}>
                    <Form.Label>Product image</Form.Label>
                    <Form.Control isInvalid={!!errors['image']} required type="text" placeholder='Product image file' name='image' onChange={handleChangeProduct} />
                    <Form.Control.Feedback type='invalid'>{errors['image']}</Form.Control.Feedback>
                </Form.Group>
            </Row>
            <Row className="mb-2">
                <Form.Group as={Col}>
                    <Form.Label>Product price</Form.Label>
                    <Form.Control isInvalid={!!errors['price']} required type="number" step="0.01" placeholder='0' name='price' onChange={handleChangeProduct} />
                    <Form.Control.Feedback type='invalid'>{errors['price']}</Form.Control.Feedback>
                </Form.Group>
            </Row>
            <Row className="mb-2">
                <Form.Group as={Col}>
                    <Form.Label>Category</Form.Label>
                    <Form.Select isInvalid={!!errors['category']} name='parent' onChange={e => setCategory(e.target.value ? categories[parseInt(e.target.value)] : null)} >
                        <option value=''></option>
                        {categories.map((category, idx) =>
                            <option key={category.id} value={idx}>{category.name}</option>
                        )}
                    </Form.Select>
                    <Form.Control.Feedback type='invalid'>{errors['category']}</Form.Control.Feedback>
                </Form.Group>
            </Row>
            <Row className="mb-3">
                <Button type="submit">Submit</Button>
            </Row>
            <Row className="mb-3">
                <p className="text-info">{response}</p>
            </Row>
        </Form>
    );

}

// MVCApi.AngularClient/src/app/product-form/product-form.component.ts
import { Component, OnInit } from '@angular/core';
import { AbstractControl, FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { Observable } from 'rxjs';
import { AddProductToCategory, CategoryDto, CategoryService, CreateProduct, ProductService } from 'src/api';
import { isEmpty } from 'src/util';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-product-form',
  templateUrl: './product-form.component.html',
  styleUrls: ['./product-form.component.css'],
})

export class ProductFormComponent implements OnInit {
  form = new FormGroup({
    name: new FormControl('', Validators.required),
    description: new FormControl('', Validators.required),
    image: new FormControl('', Validators.required),
    price: new FormControl('', [Validators.required, Validators.min(0)]),
    categories: new FormControl('', [Validators.required])
  });
  submitted : boolean = false;
  categories: Observable<CategoryDto[]> = this.categoryService.apiCategoryGetAllCategoriesGet()

  constructor(
    private readonly productService: ProductService,
    private router: Router,
    private readonly categoryService: CategoryService,
  ) {}

  ngOnInit(): void {}

  submit(): void {
    this.submitted = true;
    var createProduct: CreateProduct = this.form.value;
    var addProductToCategory : AddProductToCategory;
    if (this.form.valid) {
      this.productService
        .apiProductCreateProductPost(createProduct)
        .subscribe({
          next: (res) => {
            console.log('Added')
            addProductToCategory = {productId: res.toString(), categoryId: this.form.get('categories')?.value.toString()}
            this.categoryService.apiCategoryAddProductToCategoryPut(addProductToCategory).subscribe({
              next: (res) =>{
                console.log("Added to category");
                this.router.navigate(['/', 'products']);
              } 
            })
          },
          error: (err) => console.log(err),
        });
    }
  }

  get f(): { [key: string]: AbstractControl; }
  {
    return this.form.controls;
  }
}

<form class="mb-2" [formGroup]="form" (ngSubmit)="submit()">
    <div class="row">
      <div class="form-group col">
        <label for="name">Product name</label>
        <input
          class="form-control"
          id="name"
          name="name"
          type="text"
          formControlName="name"
          [ngClass]="{ 'is-invalid': submitted && f['name'].errors }"
          required
        />
        <div *ngIf="submitted && f['name'].errors" class="invalid-feedback">
          <div *ngIf="f['name'].errors['required']">Name is required</div>
        </div>
        </div>
  
      <div class="form-group col">
        <label for="description">Product description</label>
        <input
          class="form-control"
          name="description"
          type="text"
          formControlName="description"
          [ngClass]="{ 'is-invalid': submitted && f['description'].errors }"
          required
        />
        <div *ngIf="submitted && f['description'].errors" class="invalid-feedback">
          <div *ngIf="f['description'].errors['required']">Description is required</div>
        </div>
      </div>
  
      <div class="form-group col">
        <label for="image">Prouct image</label>
        <input
          class="form-control"
          name="image"
          type="text"
          formControlName="image"
          [ngClass]="{ 'is-invalid': submitted && f['image'].errors }"
          required
        />
        <div *ngIf="submitted && f['image'].errors" class="invalid-feedback">
          <div *ngIf="f['image'].errors['required']">Image is required</div>
        </div>
      </div>

      <div class="form-group col">
        <label for="price">Product price</label>
        <input
          class="form-control"
          name="price"
          type="number"
          formControlName="price"
          [ngClass]="{ 'is-invalid': submitted && f['price'].errors }"
          required
        />
        <div *ngIf="submitted && f['price'].errors" class="invalid-feedback">
          <div *ngIf="f['price'].errors['required']">Price is required</div>
          <div *ngIf="f['price'].errors['min']">Price must be greater than 0</div>
        </div>
      </div>

      <div class="form-group col">
        <label for="categories">Choose category</label>
        <select [ngClass]="{ 'is-invalid': submitted && f['categories'].errors }" class="form-select row" formControlName="categories">
            <option [value]="category.id" *ngFor="let category of categories | async">{{category.name}}
            </option>
         </select>
         <div *ngIf="submitted && f['categories'].errors" class="invalid-feedback">
          <div *ngIf="f['categories'].errors['required']">Category is required</div>
        </div>
      </div>

    </div>
    <button class="button btn btn-primary" type="submit">Submit</button>
  </form>
