// MVCApi.Client/src/components/CustomerEdit.tsx
import moment from 'moment'
import React, { useState, useEffect } from 'react'
import { Form, Row, Col, Button } from 'react-bootstrap'
import { CustomerDto, CustomerApi } from '../api/index'
import axios from "axios";
import { useParams } from 'react-router';

// TODO: Some nicer way to pick address and phone number

interface EditCustomerErrors {
    firstName?: string | null,
    lastName?: string | null,
    dateOfBirth?: string | null,
    country?: string | null,
    city?: string | null,
    street?: string | null,
    streetNumber?: string | null,
    postCode?: string | null,
    email?: string | null,
    phoneNumber?: string | null
}

export default function CustomerEdit(props: any) {
    //const [customer, setCustomer] = useState<EditCustomer>({})
    const { id } = useParams();
    const [customer, setCustomer] = useState<CustomerDto>({})
    const [errors, setErrors] = useState<EditCustomerErrors>({})
    const [formValue, setformValue] = useState({
        firstName: '',
        lastName: '',
        dateOfBirth: '',
        country: '',
        city: '',
        street: '',
        streetNumber: '',
        postCode: '',
        email: '',
        phoneNumber: '',
    });
    

    /*useEffect(() =>
    {
        axios.get<CustomerDto>(`http://localhost:5000/api/Customer/GetCustomerById/${id}`)
            .then(response => {
                setCustomer(response.data)
            })
        
    }, [])*/
    //XDDD
    var requestId = "";

    if(id!==undefined){
        requestId = id;
    }

    console.log("Testid: "+requestId);
    useEffect((api = new CustomerApi()) => {
        api.apiCustomerGetCustomerByIdIdGet({id: requestId}).then(response => setCustomer(response))
    }, []);

    console.log(customer.firstName);
    console.log(customer.dateOfBirth);
    console.log(moment(customer.dateOfBirth).format("YYYY-MM-DD"));

    const validation = (): boolean => {
        let valid = true
        let newErrors: EditCustomerErrors = {}

        if (!formValue.firstName) {
            newErrors.firstName = "First name must be set"
            valid = false
        } else {
            // Additional checks
        }

        if (!formValue.lastName) {
            newErrors.lastName = "Last name must be set"
            valid = false
        } else {
            // Additional checks
        }

        if (!formValue.dateOfBirth) {
            newErrors.dateOfBirth = "Date of birth must be set"
            valid = false
        } else {         
            if (moment().diff(moment(formValue.dateOfBirth), 'year') < 18) {
                newErrors.dateOfBirth = "You must be older than 18"
                valid = false
            }
            // Additional checks
        }

        if (!formValue.country) {
            newErrors.country = "Country must be set"
            valid = false
        } else {
            // Additional checks
        }

        if (!formValue.city) {
            newErrors.city = "City must be set"
            valid = false
        } else {
            // Additional checks
        }

        if (!formValue.street) {
            newErrors.street = "Street must be set"
            valid = false
        } else {
            // Additional checks
        }

        if (!formValue.streetNumber) {
            newErrors.streetNumber = "Street number must be set"
            valid = false
        } else {
            // Additional checks
        }

        if (!formValue.postCode) {
            newErrors.postCode = "Post code must be set"
            valid = false
        } else {
            // Additional checks
        }

        if (!formValue.email) {
            newErrors.email = "Email must be set"
            valid = false
        } else {
            const emailRegex = /^(([^<>()[\].,;:\s@"]+(\.[^<>()[\].,;:\s@"]+)*)|(".+"))@(([^<>()[\].,;:\s@"]+\.)+[^<>()[\].,;:\s@"]{2,})$/i;
            if (!emailRegex.test(formValue.email)) {
                newErrors.email = "Email must have a proper format"
                valid = false
            }
            // Additional checks
        }

        if (!formValue.phoneNumber) {
            newErrors.phoneNumber = "Phone number must be set"
            valid = false
        } else {
            // Additional checks
        }

        setErrors(newErrors)
        return valid
    }

    const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault()
        event.stopPropagation()

        if (validation()) {
            //let api = new CustomerApi()
            //console.log(customer.dateOfBirth)
            try {
                const response = await axios.put(`http://localhost:5000/api/Customer/EditCustomer/${id}`, formValue)
            } catch (e) {
                console.log(e)
            }
        }
    }

    const handleChangeCustomer = (event: { target: { name: any; value: any; }; }) => {
        setformValue({
          ...formValue,
          [event.target.name]: event.target.value
        });
    }

    return <Form noValidate onSubmit={handleSubmit}>
        <Row className="mb-2">
            <Form.Group as={Col}>
                <Form.Label>First name</Form.Label>
                <Form.Control defaultValue={customer.firstName?.toString()} isInvalid={!!errors['firstName']} required type="text" placeholder='First name' name='firstName' onChange={handleChangeCustomer} />
                <Form.Control.Feedback type='invalid'>{errors['firstName']}</Form.Control.Feedback>
            </Form.Group>
            <Form.Group as={Col}>
                <Form.Label>Last name</Form.Label>
                <Form.Control defaultValue={customer.lastName?.toString()} isInvalid={!!errors['lastName']} required type="text" placeholder='Last name' name='lastName' onChange={handleChangeCustomer} />
                <Form.Control.Feedback type='invalid'>{errors['lastName']}</Form.Control.Feedback>
            </Form.Group>
            <Form.Group as={Col}>
                <Form.Label>Date of birth</Form.Label>
                <Form.Control defaultValue={moment(customer?.dateOfBirth).format("YYYY-MM-DD")} isInvalid={!!errors['dateOfBirth']} required type="date" name='dateOfBirth' onChange={handleChangeCustomer} />
                <Form.Control.Feedback type='invalid'>{errors['dateOfBirth']}</Form.Control.Feedback>
            </Form.Group>
        </Row>
        <Row className="mb-2">
            <Form.Group as={Col}>
                <Form.Label>Country</Form.Label>
                <Form.Control defaultValue={customer.addresses?.pop()?.country?.toString()} isInvalid={!!errors['country']} required type="text" placeholder='Country' name='country' onChange={handleChangeCustomer} />
                <Form.Control.Feedback type='invalid'>{errors['country']}</Form.Control.Feedback>
            </Form.Group>
            <Form.Group as={Col}>
                <Form.Label>City</Form.Label>
                <Form.Control defaultValue={customer.addresses?.pop()?.city?.toString()} isInvalid={!!errors['city']} required type="text" placeholder='City' name='city' onChange={handleChangeCustomer} />
                <Form.Control.Feedback type='invalid'>{errors['city']}</Form.Control.Feedback>
            </Form.Group>    
        </Row>
        <Row>
            <Form.Group as={Col}>
                <Form.Label>Street</Form.Label>
                <Form.Control defaultValue={customer.addresses?.pop()?.street?.toString()} isInvalid={!!errors['street']} required type="text" placeholder='Street' name='street' onChange={handleChangeCustomer} />
                <Form.Control.Feedback type='invalid'>{errors['street']}</Form.Control.Feedback>
            </Form.Group>
            <Form.Group xs={1} as={Col}>
                <Form.Label>Street number</Form.Label>
                <Form.Control defaultValue={customer.addresses?.pop()?.streetNumber?.toString()} isInvalid={!!errors['streetNumber']} required type="text" placeholder='Street number' name='streetNumber' onChange={handleChangeCustomer} />
                <Form.Control.Feedback type='invalid'>{errors['streetNumber']}</Form.Control.Feedback>
            </Form.Group>
            <Form.Group xs={2} as={Col}>
                <Form.Label>Post code</Form.Label>
                <Form.Control defaultValue={customer.addresses?.pop()?.postCode?.toString()} isInvalid={!!errors['postCode']} required type="text" placeholder='Post code' name='postCode' onChange={handleChangeCustomer} />
                <Form.Control.Feedback type='invalid'>{errors['postCode']}</Form.Control.Feedback>
            </Form.Group>
        </Row>
        <Row className="mb-2">
            <Form.Group as={Col}>
                <Form.Label>Email</Form.Label>
                <Form.Control defaultValue={customer.contactInfos?.pop()?.email?.toString()} isInvalid={!!errors['email']} required type="email" placeholder='Email' name='email' onChange={handleChangeCustomer} />
                <Form.Control.Feedback type='invalid'>{errors['email']}</Form.Control.Feedback>
            </Form.Group>
            <Form.Group as={Col}>
                <Form.Label>Phone number</Form.Label>
                <Form.Control defaultValue={customer.contactInfos?.pop()?.phoneNumber?.toString()} isInvalid={!!errors['phoneNumber']} required type="text" placeholder='Phone number' name='phoneNumber' onChange={handleChangeCustomer} />
                <Form.Control.Feedback type='invalid'>{errors['phoneNumber']}</Form.Control.Feedback>
            </Form.Group>
        </Row>
        <Row className="mb-3">
            <Button type="submit">Submit</Button>
        </Row>
    </Form>
}

// MVCApi.AngularClient/src/app/customer-edit/customer-edit.component.ts
import { Component, OnInit } from '@angular/core';
import { AbstractControl, FormControl, FormGroup, Validators} from '@angular/forms';
import { EditCustomer, CustomerService, CustomerDto, AddressService, ContactInfoService, AddressDto, ContactInfoDto } from 'src/api';
import { AuthService } from '../auth.service';
import { Router, ActivatedRoute, ParamMap } from '@angular/router';
import { Observable } from 'rxjs';
import { formatDate } from '@angular/common';

@Component({
  selector: 'app-customer-edit',
  templateUrl: './customer-edit.component.html',
  styleUrls: ['./customer-edit.component.css']
})
export class CustomerEditComponent implements OnInit {
  
  form = new FormGroup({
    firstName: new FormControl('', Validators.required),
    lastName: new FormControl('', Validators.required),
    dateOfBirth: new FormControl('', [Validators.required, this.dateValidator.bind(this)]),
    country: new FormControl('', Validators.required),
    city: new FormControl('', Validators.required),
    street: new FormControl('', Validators.required),
    streetNumber: new FormControl('', Validators.required),
    postCode: new FormControl('', Validators.required),
    email: new FormControl('', [Validators.required, Validators.email]),
    phoneNumber: new FormControl('', Validators.required),
  });

  customer: Observable<CustomerDto> | null = null;
  address: Observable<AddressDto> | null = null;
  contactInfo: Observable<ContactInfoDto> | null = null;
  customerId: string = "";
  minDate : number = new Date().getFullYear() - 18;
  submitted : boolean = false; 

  constructor(
    private readonly customerService: CustomerService,
    private readonly addressService: AddressService,
    private readonly contactInfoService: ContactInfoService,
    private readonly route: ActivatedRoute,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.customerId = <string>this.route.snapshot.paramMap.get('customerId')?.toString();
    this.fetchCustomer();
  }

  submit(): void {
    this.submitted = true;
    var editCustomer: EditCustomer = this.form.value;
    if (this.form.valid) {
      this.customerService
        .apiCustomerEditCustomerIdPut(this.customerId, editCustomer)
        .subscribe({
          next: (res) => {
            this.router.navigate(['/', 'customers']);
          },
        });
    }
  }

  private fetchCustomer(): void {
    this.customer = this.customerService.apiCustomerGetCustomerByIdIdGet(
      this.customerId, 
    )

    this.customer.subscribe(
      res => {

        this.form.patchValue({firstName: res.firstName});
        this.form.patchValue({lastName: res.lastName});
        this.form.patchValue({dateOfBirth: formatDate(<string>res.dateOfBirth, "YYYY-MM-dd", "en-US")});
        console.log(formatDate(<string>res.dateOfBirth, "YYYY-MM-dd", "en-US"))

        this.address = this.addressService.apiAddressGetAddressByIdIdGet(
          <string>res.addresses![0].id?.toString(),
        )

        this.address.subscribe(
          res => {
            this.form.patchValue({country: res.country});
            this.form.patchValue({city: res.city});
            this.form.patchValue({street: res.street});
            this.form.patchValue({streetNumber: res.streetNumber});
            this.form.patchValue({postCode: res.postCode});
          }
        )

        this.contactInfo = this.contactInfoService.apiContactInfoGetContactInfoByIdIdGet(
          <string>res.contactInfos![0].id?.toString(),
        )

        this.contactInfo?.subscribe(
          res => {
            this.form.patchValue({email: res.email});
            this.form.patchValue({phoneNumber: res.phoneNumber});
          }
        )

      }
    )
  }

  get f(): { [key: string]: AbstractControl; }
  {
    return this.form.controls;
  }

  dateValidator(control: FormControl): { [s: string]: boolean } | null {
    if (control.value) {
      const date = new Date(this.form.controls['dateOfBirth'].value);
      const dateYr = date.getFullYear();
      const minDate = this.minDate;
      
      if (minDate<=dateYr) {
        return { 'invalidDate': true }
      }
    }
    return null;
  }
}

<form class="mb-2" [formGroup]="form" (ngSubmit)="submit()">
  <div class="row">
    <div class="form-group col">
      <label for="firstName">First name</label>
      <input
        class="form-control"
        name="firstName"
        type="text"
        formControlName="firstName"
        [ngClass]="{ 'is-invalid': submitted && f['firstName'].errors }"
        required
      />
      <div *ngIf="submitted && f['firstName'].errors" class="invalid-feedback">
        <div *ngIf="f['firstName'].errors['required']">First name is required</div>
      </div>
    </div>

    <div class="form-group col">
      <label for="lastName">Last name</label>
      <input
        class="form-control"
        name="lastName"
        type="text"
        formControlName="lastName"
        [ngClass]="{ 'is-invalid': submitted && f['country'].errors }"
        required
      />
      <div *ngIf="submitted && f['lastName'].errors" class="invalid-feedback">
        <div *ngIf="f['lastName'].errors['required']">Last name is required</div>
      </div>
    </div>

    <div class="form-group col">
      <label for="dateOfBirth">Date of birth</label>
      <input
        class="form-control"
        name="dateOfBirth"
        type="date"
        formControlName="dateOfBirth"
        [ngClass]="{ 'is-invalid': submitted && f['dateOfBirth'].errors }"
        required
      />
      <div *ngIf="submitted && f['dateOfBirth'].errors" class="invalid-feedback">
          <div *ngIf="f['dateOfBirth'].errors['required']">Date of birth is required</div>
          <div *ngIf="f['dateOfBirth'].errors['invalidDate']">Customer must be over 18</div>
        </div>
    </div>
  </div>

  <div class="row">
    <div class="form-group col">
      <label for="country">Country</label>
      <input
        class="form-control"
        name="country"
        type="text"
        formControlName="country"
        [ngClass]="{ 'is-invalid': submitted && f['country'].errors }"
        required
      />
      <div *ngIf="submitted && f['country'].errors" class="invalid-feedback">
        <div *ngIf="f['country'].errors['required']">Country is required</div>
      </div>
    </div>

    <div class="form-group col">
      <label for="city">City</label>
      <input
        class="form-control"
        name="city"
        type="text"
        formControlName="city"
        [ngClass]="{ 'is-invalid': submitted && f['city'].errors }"
        required
      />
      <div *ngIf="submitted && f['city'].errors" class="invalid-feedback">
        <div *ngIf="f['city'].errors['required']">City is required</div>
      </div>
    </div>

    <div class="form-group col">
      <label for="street">Street</label>
      <input
        class="form-control"
        name="street"
        type="text"
        formControlName="street"
        [ngClass]="{ 'is-invalid': submitted && f['street'].errors }"
        required
      />
      <div *ngIf="submitted && f['street'].errors" class="invalid-feedback">
        <div *ngIf="f['street'].errors['required']">Street is required</div>
      </div>
    </div>

    <div class="form-group col">
      <label for="streetNumber">Street number</label>
      <input
        class="form-control"
        name="streetNumber"
        type="text"
        formControlName="streetNumber"
        [ngClass]="{ 'is-invalid': submitted && f['streetNumber'].errors }"
        required
      />
      <div *ngIf="submitted && f['streetNumber'].errors" class="invalid-feedback">
        <div *ngIf="f['streetNumber'].errors['required']">Street number is required</div>
      </div>
    </div>

    <div class="form-group col">
      <label for="postCode">Post code</label>
      <input
        class="form-control"
        name="postCode"
        type="text"
        formControlName="postCode"
        [ngClass]="{ 'is-invalid': submitted && f['postCode'].errors }"
        required
      />
      <div *ngIf="submitted && f['postCode'].errors" class="invalid-feedback">
        <div *ngIf="f['postCode'].errors['required']">Postcode is required</div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="form-group col">
      <label for="email">Email</label>
      <input
        class="form-control"
        name="email"
        type="email"
        formControlName="email"
        [ngClass]="{ 'is-invalid': submitted && f['email'].errors }"
        required
      />
      <div *ngIf="submitted && f['email'].errors" class="invalid-feedback">
        <div *ngIf="f['email'].errors['required']">E-mail is required</div>
        <div *ngIf="f['email'].errors['email']">E-mail is invalid</div>
      </div>
    </div>

    <div class="form-group col">
      <label for="phoneNumber">Phone number</label>
      <input
        class="form-control"
        name="phoneNumber"
        type="text"
        formControlName="phoneNumber"
        [ngClass]="{ 'is-invalid': submitted && f['phoneNumber'].errors }"
        required
      />
      <div *ngIf="submitted && f['phoneNumber'].errors" class="invalid-feedback">
        <div *ngIf="f['phoneNumber'].errors['required']">Phone number is required</div>
      </div>
    </div>
  </div>

  <button class="button btn btn-primary" type="submit">Submit</button>
</form>
