// MVCApi.AngularClient/src/app/category-tree/category-tree.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { CategoryDto } from 'src/api';

@Component({
  selector: 'app-category-tree',
  templateUrl: './category-tree.component.html',
  styleUrls: ['./category-tree.component.css']
})
export class CategoryTreeComponent implements OnInit {
  @Input() category: CategoryDto | undefined;

  constructor() { }

  ngOnInit(): void {
  }

}

<ul class="list-group">
  <li *ngIf="category" class="list-group-item list-group-item-action">
    <a
      class="text-decoration-none font-weight-bold text-reset category-tree-element"
      routerLink="/categories/{{ category.id }}"
      >{{ category.name }}</a
    >
    <div *ngFor="let child of category.children">
      <app-category-tree [category]="child"></app-category-tree>
    </div>
  </li>
</ul>

// MVCApi.Client/src/components/CategoryTree.tsx
import React from "react";
import { Link } from "react-router-dom";
import { CategoryDto } from "../api";

type CategoryTreeProps = {
    category: CategoryDto
}

export default function CategoryTree({ category }: CategoryTreeProps) {
    return (
        <>
            <ul className="list-group">
                <li className="list-group-item list-group-item-action" key={category.id} >
                    <Link
                        className='text-decoration-none font-weight-bold text-reset'
                        to={{ pathname: '/products', state: { categoryId: category.id } }}                        
                        style={{ width: '100%', display: "block", height: '100%' }}
                        
                    >
                        <span>{category.name}</span>
                    </Link>
                    {category.children && category.children.map(child =>
                        <CategoryTree key={child.id} category={child} />
                    )}
                </li>
            </ul>
        </>
    )
}
