// MVCApi.AngularClient/src/app/category-form/category-form.component.ts
import { Component, OnInit } from '@angular/core';
import { AbstractControl, FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { Observable } from 'rxjs';
import { CategoryDto, CategoryService, CreateCategory, CreateSubcategory } from 'src/api';

@Component({
  selector: 'app-category-form',
  templateUrl: './category-form.component.html',
  styleUrls: ['./category-form.component.css']
})
export class CategoryFormComponent implements OnInit {
  form = new FormGroup({
    name: new FormControl('', Validators.required),
    parent: new FormControl(''),
    isChild: new FormControl(false),
  });
  submitted : boolean = false;
  isSubCategory : boolean = false;
  parent : any = null;
  checked : boolean = false;

  constructor( 
    private readonly categoryService: CategoryService,
    private router: Router
    ) { }

  categories: Observable<CategoryDto[]> = this.categoryService.apiCategoryGetAllCategoriesGet()

  ngOnInit(): void {
  }

  get f(): { [key: string]: AbstractControl; }
  {
    return this.form.controls;
  }

  toggleEditable(event: { target: { checked: any; }; }) {
    if ( event.target.checked ) {
      this.isSubCategory = true;
    }
    else {
      this.isSubCategory = false;
    }
    console.log(this.isSubCategory);
  }


  submit():void{
    if (this.form.valid) {
      //If is not a child
      var createCategory: CreateCategory = this.form.value;
      if(this.form.get('isChild')?.value===false){
        this.categoryService
        .apiCategoryCreateCategoryPost(createCategory)
        .subscribe({
          next: () => {
            this.router.navigate(['/', 'categories']);
            console.log('Added')
          },
          error: (err) => console.log(err),
        });
      }
      //If is a child
      else{
        var createSubcategory: CreateSubcategory = {name: this.form.get('name')?.value.toString(), parentId: this.form.get('parent')?.value.toString()}

        this.categoryService
        .apiCategoryCreateSubcategoryPost(createSubcategory)
        .subscribe({
          next: () => {
            this.router.navigate(['/', 'categories']);
            console.log('Added sub')
          },
          error: (err) => console.log(err),
        });
      }
      
    }
  }
}

<form class="mb-2" [formGroup]="form" (ngSubmit)="submit()">
    <div class="row">
      <div class="form-group col">
        <label for="name">Category name</label>
        <input
          class="form-control"
          id="name"
          name="name"
          type="text"
          formControlName="name"
          [ngClass]="{ 'is-invalid': submitted && f['name'].errors }"
          required
        />
        <div *ngIf="submitted && f['name'].errors" class="invalid-feedback">
          <div *ngIf="f['name'].errors['required']">Name is required</div>
        </div>
        </div>
  
      <div class="form-group col col-md-4">
        <label class="form-check-label row" for="isChild">Is it subcategory?</label>
        <input
          class="form-check-input row"
          name="isChild"
          type="checkbox"
          [(ngModel)]="checked"
          formControlName="isChild"
        />
      </div>
  
      <div class="form-group col">
        <label for="parent">Choose parent</label>
        <select class="form-select row" [disabled]="!checked" formControlName="parent">
            <option value="" disabled>Choose parent category</option>
            <option [disabled]="!checked" [value]="category.id" *ngFor="let category of categories | async">{{category.name}}
            </option>
         </select>
      </div>
    </div>
    <button class="button btn btn-primary" type="submit">Submit</button>
  </form>

// MVCApi.Client/src/components/CategoryForm.tsx
import React, { useState, useEffect } from 'react'
import { Form, Row, Col, Button } from 'react-bootstrap'
import { CategoryApi, CategoryDto } from '../api'

interface CategoryErrors {
    name?: string | null
    parent?: string | null
}

type CategoryFormProps = {
    added: boolean
    setAdded: React.Dispatch<React.SetStateAction<boolean>>
}

export function CategoryForm({ added, setAdded }: CategoryFormProps) {
    const [categoryName, setCategoryName] = useState<string>("")
    const [parent, setParent] = useState<CategoryDto | null>(null)
    const [categories, setCategories] = useState<CategoryDto[]>([])
    const [isChild, setIsChild] = useState<boolean>(false)
    const [errors, setErrors] = useState<CategoryErrors>({})

    const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {

        let valid = true;
        let newErrors: CategoryErrors = {}
        e.preventDefault()

        if (isChild) {
            if (!parent) {
                valid = false;
                newErrors.parent = "You must select parent when creating subcategory"
            }
        }

        if (!categoryName) {
            valid = false;
            newErrors.name = "Category name cannot be empty"
        }

        setErrors(newErrors)

        if (valid) {
            const api = new CategoryApi()
            if (!isChild) {
                api.apiCategoryCreateCategoryPost({ createCategory: { name: categoryName } })
                    .then(r => setAdded(!added))
            } else {
                api.apiCategoryCreateSubcategoryPost({ createSubcategory: { name: categoryName, parentId: parent?.id } })
                    .then(r => setAdded(!added))
            }
        }
    }

    useEffect(() => {
        const api = new CategoryApi()
        api.apiCategoryGetAllCategoriesGet()
            .then(response => {
                setCategories(response)
            })
    }, [added])

    return (
        <Form noValidate onSubmit={e => handleSubmit(e)}>
            <Row className="mb-2 input-group">
                <Form.Group as={Col}>
                    <Form.Label>Category name</Form.Label>
                    <Form.Control isInvalid={!!errors['name']} required type="text" placeholder='Category name' name='name' onChange={e => setCategoryName(e.target.value)} />
                    <Form.Control.Feedback type='invalid'>{errors['name']}</Form.Control.Feedback>
                </Form.Group>
                <Form.Group as={Col}>
                    <Form.Label>Is subcategory?</Form.Label>
                    <Form.Check type='checkbox' name='isChild' onChange={(e) => setIsChild(e.target.checked)} />
                </Form.Group>
                <Form.Group as={Col}>
                    <Form.Label>Parent category</Form.Label>
                    <Form.Select isInvalid={!!errors['parent']} name='parent' disabled={!isChild} onChange={e => setParent(e.target.value ? categories[parseInt(e.target.value)] : null)} >
                        <option value=''></option>
                        {categories.map((category, idx) =>
                            <option key={category.id} value={idx}>{category.name}</option>
                        )}
                    </Form.Select>
                    <Form.Control.Feedback type='invalid'>{errors['parent']}</Form.Control.Feedback>
                </Form.Group>
                <div className="col align-self-end">
                    <Button type="submit">Submit</Button>
                </div>
            </Row>
        </Form>
    )

}
