// MVCApi.AngularClient/src/app/pagination/pagination.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-pagination',
  templateUrl: './pagination.component.html',
  styleUrls: ['./pagination.component.css'],
})
export class PaginationComponent implements OnInit {
  @Input() pageIndex: number = 1;
  @Input() totalPages: number = 1;
  @Input() hasPreviousPage: boolean = false;
  @Input() hasNextPage: boolean = false;

  rangeWithDots: Array<string | number> = [];

  constructor() {}

  ngOnInit(): void {
    this.calculateRange();
  }

  ngOnChange() {
    this.calculateRange();
  }

  private calculateRange() {
    var current = this.pageIndex,
      last = this.totalPages,
      delta = 2,
      left = current - delta,
      right = current + delta + 1,
      range = [],
      rangeWithDots = [],
      l;

    for (let i = 1; i <= last; i++) {
      if ((i === 1 || i === last || i >= left) && i < right) {
        range.push(i);
      }
    }

    for (let i of range) {
      if (l) {
        if (i - l === 2) {
          rangeWithDots.push(l + 1);
        } else if (i - l !== 1) {
          rangeWithDots.push('...');
        }
      }
      rangeWithDots.push(i);
      l = i;
    }

    console.log(rangeWithDots);
    this.rangeWithDots = rangeWithDots;
  }
}

<nav>
  <ul class="pagination justify-content-center">
    <li *ngIf="hasPreviousPage" class="page-item">
      <span class="page-link">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </span>
    </li>

    <li *ngFor="let item in rangeWithDots" class="page-item">
      <span class="page-link">{{ item }}</span>
    </li>

    <li *ngIf="hasNextPage" oclassName="page-item">
      <span class="page-link">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </span>
    </li>
  </ul>
</nav>

// MVCApi.Client/src/components/Pagination.tsx
import React from 'react'

type PaginationProps = {
    pageIndex: number,
    totalPages: number,
    hasNextPage: boolean,
    hasPreviousPage: boolean
}

export default function Pagination({  pageIndex, totalPages, hasNextPage, hasPreviousPage }: PaginationProps) {
    var current = pageIndex,
        last = totalPages,
        delta = 2,
        left = current - delta,
        right = current + delta + 1,
        range = [],
        rangeWithDots = [],
        l;

    for (let i = 1; i <= last; i++) {
        if (i == 1 || i == last || i >= left && i < right) {
            range.push(i);
        }
    }

    for (let i of range) {
        if (l) {
            if (i - l === 2) {
                rangeWithDots.push(l + 1);
            } else if (i - l !== 1) {
                rangeWithDots.push('...');
            }
        }
        rangeWithDots.push(i);
        l = i;
    }

    return (
        <nav>
            <ul className='pagination justify-content-center'>
                {hasPreviousPage &&
                    <li className="page-item">
                        <span aria-hidden="true">&laquo;</span>
                        <span className="sr-only">Previous</span>
                    </li>}
                {rangeWithDots.map((i, k) => 
                    <li className="page-item" key={k}>
                        <span className="page-link">{i}</span>
                    </li>
                )}

                {hasNextPage &&
                    <li className="page-item">
                        <span aria-hidden="true">&raquo;</span>
                        <span className="sr-only">Next</span>
                    </li>}
            </ul>
        </nav>
    )
}
