// MVCApi.AngularClient/src/app/products/products.component.ts
import { getLocaleCurrencyCode } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import {
  CartService,
  CategoryDto,
  CategoryService,
  ProductDto,
  ProductDtoIPaginatedList,
  ProductService,
} from 'src/api';
import { ShoppingCartService } from '../shopping-cart.service';

@Component({
  selector: 'app-products',
  templateUrl: './products.component.html',
  styleUrls: ['./products.component.css'],
})
export class ProductsComponent implements OnInit {
  products: Observable<ProductDtoIPaginatedList> | null = null;
  categories: Observable<CategoryDto[]> =
    this.categoryService.apiCategoryGetRootCategoriesGet();

  categoryId: string | null = null;

  pageIndex: number = 1;
  pageSize: number = 10;
  totalPages: number = 1
  hasNextPage: boolean = false
  hasPreviousPage: boolean = false

  constructor(
    private readonly productService: ProductService,
    private readonly categoryService: CategoryService,
    private readonly cartService: CartService,
    private readonly shoppingCartService: ShoppingCartService,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.route.queryParams.subscribe((params) => {
      this.categoryId = params['categoryId'];
      if (this.categoryId) {
        this.products =
          this.productService.apiProductGetPaginatedProductsByCategoryGet(
            this.pageIndex,
            this.pageSize,
            getLocaleCurrencyCode(navigator.language) ?? 'PLN',
            this.categoryId
          );
      } else {
        this.products = this.productService.apiProductGetPaginatedProductsGet(
          this.pageIndex,
          this.pageSize,
          getLocaleCurrencyCode(navigator.language) ?? 'PLN'
        );
      }
      
      this.products.subscribe({
        next: (res) =>
        {
          this.pageIndex = res.pageIndex ?? 1
          this.pageSize = res.pageSize ?? 10
          this.totalPages = res.totalPages ?? 1
          this.hasNextPage = res.hasNextPage ?? false
          this.hasPreviousPage = res.hasPreviousPage ?? false
        }
      })
    });
  }

  addToCart(id: string | undefined) {
    if (!id) return;

    this.shoppingCartService.getOrCreateCart().then((cart) => {
      this.cartService
        .apiCartAddProductToCartPut({
          cartId: cart?.id,
          productId: id,
          count: 1,
        })
        .subscribe({
          next: () => console.log('Added'),
          error: (err) => console.log(err),
        });
    });
  }
}

<div class="row">
  <div class="col-lg-3">
    <div *ngFor="let category of categories | async">
      <app-category-tree [category]="category"></app-category-tree>
    </div>
  </div>

  <div *ngIf="products" class="col-lg-9">
    <div *ngFor="let product of (products | async)?.items" class="row product">
      <app-product class="col-md-10" [product]="product"></app-product>
      <div class="col-md-2">
        <button class="btn btn-primary" (click)="addToCart(product.id)">
          Add to cart
        </button>
      </div>
    </div>
    <app-pagination
      [pageIndex]="pageIndex"
      [totalPages]="totalPages"
      [hasNextPage]="hasNextPage"
      [hasPreviousPage]="hasPreviousPage"
    ></app-pagination>
  </div>
</div>

// MVCApi.Client/src/components/Products.tsx
import React, { useEffect, useState } from 'react'
import { ProductDto, ProductApi, CartApi, ProductDtoIPaginatedList, CategoryDto, CategoryApi } from '../api'
import { getOrCreateCart } from '../util/CartUtil';
import { useIntl } from 'react-intl'
import LocaleCurrency from 'locale-currency'
import { useLocation } from 'react-router';
import { ProductSmall, Pagination, CategoryTree } from './';

type ProductsProps = {
    categoryId?: string
}

export function Products() {
    const [products, setProducts] = useState<ProductDto[] | []>([])
    const [pagination, setPagination] = useState<ProductDtoIPaginatedList>({})
    const [page, setPage] = useState<Number>(1)
    const [pageSize, setPageSize] = useState<Number>(25)
    const intl = useIntl()
    const location = useLocation<ProductsProps>()
    const categoryId = location.state?.categoryId
    const [categories, setCategories] = useState<CategoryDto[]>([])

    useEffect((api = new ProductApi()) => {
        const categoryApi = new CategoryApi()
        const args: any = {
            pageNumber: page.valueOf(),
            pageSize: pageSize.valueOf(),
            currencyCode: LocaleCurrency.getCurrency(intl.locale)
        }

        if (categoryId) {
            args['categoryId'] = categoryId
            api.apiProductGetPaginatedProductsByCategoryGet(args)
                .then(response => {
                    setPagination(response)
                    setProducts(response.items!)
                })
            categoryApi.apiCategoryGetCategoryByIdIdGet({id: categoryId})
                .then(response => {
                    setCategories([response])
                })
        } else {
            api.apiProductGetPaginatedProductsGet(args)
                .then(response => {
                    setPagination(response)
                    setProducts(response.items!)
                })
            categoryApi.apiCategoryGetRootCategoriesGet()
                .then(response => {
                    setCategories(response)
                })
        }
    }, [intl.locale, page, pageSize, categoryId]);

    const handleAdd = (e: React.MouseEvent<HTMLElement>, productId: string) => {
        const api = new CartApi()

        getOrCreateCart(LocaleCurrency.getCurrency(intl.locale))
            .then(response => {
                if (response.products?.filter(p => p.product?.id === productId).length === 0) {
                    api.apiCartAddProductToCartPut({ addProductToCart: { cartId: response.id, productId: productId, count: 1 } })
                        .catch(e => console.log(e))
                }
            })
            .catch(e => console.log(e))
    }  

    return (
        <>
            <div className="row">
                <div className="col-lg-3">                    
                    {categories.map(category =>
                        <CategoryTree category={category} />
                    )}
                </div>
                <div className="col-lg-9">
                    {products.map(product => (
                        <div key={product.id} className="row product">
                            <ProductSmall product={product} />
                            <div className="col-md-2">
                                <button className='btn btn-primary' onClick={(e) => handleAdd(e, product.id!)}>Add to cart</button>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
            <Pagination
                pageIndex={pagination.pageIndex?.valueOf()!}
                totalPages={pagination.totalPages?.valueOf()!}
                hasNextPage={pagination.hasNextPage!}
                hasPreviousPage={pagination.hasPreviousPage!}
                setPage={setPage}
                setPageSize={setPageSize}
            />
        </>
    );
}
